### ISSUE TITLE
Hey Chad

### ISSUE THREAD

**Issue by artp** [chadsmith/OpenVBX-Plugin-Subscriptions#1]
Hello Chad and all,
I'm new here and dont really understand code, but I figured I would ask the questions here
so here goes:

I'm getting these errors:
A PHP Error was encountered
Severity: Notice
Message: Undefined index: remove
Filename: chadsmith-OpenVBX-Plugin-Subscriptions-dc33360/subscriptions.php
Line Number: 9

A PHP Error was encountered
Severity: Notice
Message: Undefined index: list
Filename: chadsmith-OpenVBX-Plugin-Subscriptions-dc33360/subscriptions.php
Line Number: 21

A PHP Error was encountered
Severity: Notice
Message: Undefined index: list
Filename: chadsmith-OpenVBX-Plugin-Subscriptions-dc33360/subscriptions.php
Line Number: 32

A PHP Error was encountered
Severity: Notice
Message: Undefined index: export
Filename: chadsmith-OpenVBX-Plugin-Subscriptions-dc33360/subscriptions.php
Line Number: 44

A PHP Error was encountered
Severity: Notice
Message: Undefined index: name
Filename: chadsmith-OpenVBX-Plugin-Subscriptions-dc33360/subscriptions.php
Line Number: 55

How should I go about fixing this?
I know how to do basic fixes
Can someone please help

thanks art

**Comment by that0n3guy** [comment]
I am also getting this error on version .91.  Don't think I have that error on my .83 install.

**Comment by jchosler** [comment]
I have the same error as well. Using v0.90 r47. The error also appears in the Polls plugin.

**Comment by alatteri** [comment]
same here.

**Comment by chadsmith** [comment]
This is due to notices being turned on in index.php. You can turn them off by making this change [here](https://github.com/chadsmith/OpenVBX/commit/ac4e73f5c52ef066c98e55a7f8559fa7a0a6782c).
