### ISSUE TITLE
Not adding subscribers to list during flow

### ISSUE THREAD

**Issue by maddenm** [chadsmith/OpenVBX-Plugin-Subscriptions#11]
I have tried the latest version, the forked version, and earlier versions and can not get it to work on HostGator.  I can import subscriber numbers successfully.

**Comment by chadsmith** [comment]
Any chance you're using an SMS flow with the keyword start or subscribe? If so, you might talk to Twilio about modifying your account. I believe they made those reserved words on new accounts.

**Comment by maddenm** [comment]
Thanks for the reply, Chad!  I set up a simple flow that does nothing but add the number to the subscription list.  I am not using any keywords.

**Comment by chadsmith** [comment]
Strange. I just tested subscribing to an SMS and voice flow and it added me. [Email me](mailto:chad@nospam.me) with additional details regarding your setup (i.e. OpenVBX version, host, list name, sender area code, etc).

**Comment by chadsmith** [comment]
It wasn't adding them because Twilio no longer sends Direction on incoming SMSs. I just pushed an update to fix that.
