### ISSUE TITLE
Subscription Plugin not adding numbers to list

### ISSUE THREAD

**Issue by zephirinmg** [chadsmith/OpenVBX-Plugin-Subscriptions#12]
Hey chad hows it going buddy.I installed the subscription plugin but it does not seem to work no matter what I try.I first tried the "If member" applet to add new numbers to the list but that didn't work.I then tried to automatically add any number that sends a text to the list by directly starting the flow with the subscribe applet, but that didn't work either.My host is dream host.Everything seems to work fine including your match plugin.Any idea how I can go about solving this?Thanks!

I tried both installing openvbx on a sub-domain and a sub directory but to no avail

EDIT: The plugin works fine in a call flow, but the problems arise in an sms flow.

**Comment by chadsmith** [comment]
It wasn't adding them because Twilio no longer sends Direction on incoming SMSs. I just pushed an update to fix that.
