### ISSUE TITLE
PHP errors

### ISSUE THREAD

**Issue by alatteri** [chadsmith/OpenVBX-Plugin-Subscriptions#3]
getting a bunch of PHP errors showing up in the interface.  things seem to work though.  you can see a snapshot of it here http://i.imgur.com/2RKhI.png

A PHP Error was encountered
Severity: Notice
Message: Undefined index: remove
Filename: subscription/subscriptions.php
Line Number: 9
A PHP Error was encountered
Severity: Notice
Message: Undefined index: list
Filename: subscription/subscriptions.php
Line Number: 21
A PHP Error was encountered
Severity: Notice
Message: Undefined index: list
Filename: subscription/subscriptions.php
Line Number: 32
A PHP Error was encountered
Severity: Notice
Message: Undefined index: export
Filename: subscription/subscriptions.php
Line Number: 44
A PHP Error was encountered
Severity: Notice
Message: Undefined index: name
Filename: subscription/subscriptions.php
Line Number: 55

**Comment by chadsmith** [comment]
This is due to notices being turned on in index.php. You can turn them off by making this change [here](https://github.com/chadsmith/OpenVBX/commit/ac4e73f5c52ef066c98e55a7f8559fa7a0a6782c).
