### ISSUE TITLE
Javascript error with "If member"

### ISSUE THREAD

**Issue by sglas** [chadsmith/OpenVBX-Plugin-Subscriptions#4]
Hi, awesome plugins, thanks.

Just testing with If Member and If User, and when I try to drag these into an OpenVBX flow it 'hangs' - the icon doesn't resolve to have an flow options and the icon sticks on the screen until I refresh.

I get the following in Firefox 5:

d is null
d=$("#prototypes #prototype-"+c.type)....option","buttons",{OK:function(){e(); 
flow.js (Line 15)

In Safari:

ReferenceError: Can't find variable: $
TypeError: 'null' is not an object (evaluating 'd.replace')  (flow.js (Line 15))

$(".subflow-applet input[type=radio]").live('click', function(event) {
2:1792ReferenceError: Can't find variable: $
            var tr = $(this).closest('tr');

Any thoughts?

**Comment by chadsmith** [comment]
The If Member and If User applets don't use any JavaScript, so it's not
caused by those.

Try removing the Transfer plugin and see if that fixes it.

**Comment by sglas** [comment]
Thanks for the tip. It seems that the plugin OpenVBX-Plugin-Outbound was actually causing the conflict - removing this made Subscriptions work.
