### ISSUE TITLE
Action Icons Missing Under Manage Lists

### ISSUE THREAD

**Issue by veterantech** [chadsmith/OpenVBX-Plugin-Subscriptions#5]
When I click on Manage Lists the SMS, Call and Delete icons are missing.  I can hover over the area, click and perform the action. The same thing happens when I expand down to the individual subscribers.  You can hover over and click where the icon is supposed to be and the action is performed, but the icons are missing.

**Comment by tonypearl** [comment]
Yeah, I actually have that same problem, too.

A minor inconvenience, but one you might want to be aware of nonetheless.

Thanks!

**Comment by dasilvatek** [comment]
This is a quick fix for anyone as I just found out:
Edit "subscriptions.php"
Search for the two occurrences of "/assets"
Replace with "/openvbx/assets"
and the icons appear... enjoy!

**Comment by binaryatlas** [comment]
just ../ in front of assets fixed this for me

**Comment by chadsmith** [comment]
I'm guessing you had OpenVBX in a subdirectory. I just pushed an update to fix this.
