### ISSUE TITLE
Scheduled Flow calls & Hangs up when call is answered...

### ISSUE THREAD

**Issue by tonypearl** [chadsmith/OpenVBX-Plugin-Subscriptions#6]
Hey Chad,

LOVE your work, man!

Ok, so I finally got the 'scheduled flow' to work (even though it doesn't call at the time scheduled).
But when the flow goes out, it just HANGS UP on the caller as soon as they pick up!
(It used to work, but now it doesn't. I'm not sure, but I think that the latest update may have thrown something out of whack)

I'm using OpenVBX • v1.1.2 r63
And I'm on Hostgator.

To retrace my steps,
Here's what I'm doing:

First, I go to:
-->Subscriptions-->Schedule Update-->Add Call.
Under 'Schedule Call,' I pick a list, a date/time, a flow, the right number caller id to associate with it,
then execute it by clicking on 'Add'.

When the call comes in,
I pick up the phone, and hear 'clack!' as it hangs up in my ear, instead of the Call Flow
I had scheduled.
How can this be fixed??

Ok, I just noticed that I'm getting this message:
ERROR 11100: Invalid URL format

So I went to 'Debugger' and saw this message:
The specified url
http://twiml/start/voice/8
is invalid.

I think the code in the 'Subscriptions' plugin is messed up somewhere.
I'm going to investigate it myself, even though I'm no coder.
But it looks to me like the path is just wrong.

The curious thing is that when you go to 'Subscriptions'-->'Manage Lists',
and do the same thing, it goes out right away, but works perfectly!!

Did I mention that I'm on Hostgator?

Next question: How can I get the 'scheduled updates' to go out AT THE TIME THEY'RE SUPPOSED TO??
For some crazy reason, that just doesn't seem to work for me correctly.

I absolutely LOVE OpenVBX & Twilio, but there's just SO many issues with this that it's driving me nuts.
But for what it's worth, I really hope that the coders here are able to get them all worked out soon.
I have SO many plans & possibilities for this!

I'll try to come back here & post what I find, especially if I'm able to fix anything.

OF course, if anyone else has success or knows wtf is going on w/ the issues I'm having, 
please, please please share what you know!!

Thanks Chad,

Tony

**Comment by chadsmith** [comment]
It sounds like there's an issue with how Hostgator handles OpenVBX's site_url function in the [Outbound Flows](https://github.com/chadsmith/OpenVBX-Plugin-Outbound/blob/master/queue.php#L16) plugin rather than it being something in the Subscriptions plugin.

Are you using a cron job? If so, is it loading via the script (i.e. */5 \* \* \* \* /usr/bin/php5 /PATH_TO_OPENVBX/plugins/outbound/cron.php) or URL (http://YOUR_DOMAIN/hook/outbound/cron)? Also, does it work when you just start a flow using the Outbound plugin?

**Comment by chadsmith** [comment]
Nevermind, I noticed Shawn Parker posted a solution on the issue in the Outbound Flows plugin. I will add that to the documention. Thanks!
