### ISSUE TITLE
Scheduling 

### ISSUE THREAD

**Issue by Myszak** [chadsmith/OpenVBX-Plugin-Subscriptions#8]
After saving a schedule there is not a list.. How can I tell if the calls were made?

**Comment by chadsmith** [comment]
You need to use this with my [Outbound Flows plugin](https://github.com/chadsmith/OpenVBX-Plugin-Outbound) to schedule calls.

**Comment by Myszak** [comment]
Thanks Chad... I have the outbound.. but it didn't send..... Thanks for
all  the work on the plugins.. I have decided to use a dialer that is a bit
more robust and scaleable...
On Jul 10, 2012 4:11 PM, "Chad Smith" <
reply@reply.github.com>
wrote:
