### ISSUE TITLE
I use the Dispatch feature... get error.

### ISSUE THREAD

**Issue by xkaluv** [chadsmith/OpenVBX-Plugin-Subscriptions#9]
I use the Dispatch feature to SMS a Txt that I want to deliver to multiple subscribers.  I get an error back via txt every time that says "An unknown error occurred. Please contact the an administrator. "  However, the text still completes and appears to get to all of my subscribers, any ideas?

I also logged into Twilio and was able to see this error.... (Note: I omitted the base URL, can supply in private message.)
Error - 11205 - HTTP connection failure
An attempt to retrieve TwiML from http://[omitted baseURL]/twiml/applet/sms/2/ddaa5c failed; the connection timed out. Please check the URL and your network settings and try again.

**Comment by xkaluv** [comment]
I get this same error.

**Comment by chadsmith** [comment]
The Dispatch applet was programmed to send the messages before sending a response to Twilio. If you're texting a large set of numbers, it was likely timing out on Twilio's end before the messages were sent. I reversed the order so it sends a response first and then sends the texts.
